### ISSUE TITLE
Can't install extension and errors are not descriptive

### ISSUE THREAD

**Issue by samuela** [cdr/sshcode#152]
I just tried installing the "rust-lang.rust" extension, but immediately I get an error: "Failed to install "rust-lang.rust".". This strikes me as especially odd, since I can use VSCode's "Remote SSH" feature and install the extension without any hiccup on the exact same server. 

It's also not at all clear what's going wrong here. The error message is not very descriptive but I opened up the DevTools console and it has a little something:
```
Error
(anonymous) @ extensionsActions.ts:252
Promise.then (async)
install @ extensionsActions.ts:247
run @ extensionsActions.ts:221
run @ extensionsActions.ts:482
runAction @ actions.ts:216
run @ actions.ts:208
onClick @ actionbar.ts:168
(anonymous) @ actionbar.ts:138
Promise.then (async)
(anonymous) @ platform.ts:181
(anonymous) @ actionbar.ts:138

Failed to install 'rust-lang.rust'.
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:580
addNotification @ notifications.ts:156
notify @ notificationService.ts:100
prompt @ notificationService.ts:165
re @ extensionsActions.ts:82
(anonymous) @ extensionsActions.ts:254
Promise.then (async)
install @ extensionsActions.ts:247
run @ extensionsActions.ts:221
run @ extensionsActions.ts:482
runAction @ actions.ts:216
run @ actions.ts:208
onClick @ actionbar.ts:168
(anonymous) @ actionbar.ts:138
Promise.then (async)
(anonymous) @ platform.ts:181
(anonymous) @ actionbar.ts:138

log.ts:196   ERR unable to get local issuer certificate: downloading: unable to get local issuer certificate
    at galleryService.download.then.e (/src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/cli.js:377:220)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm running Linux host, Linux remote.

**Comment by Merith-TK** [comment]
I feel as if this is a issue for normal [Code-Server](https://github.com/cdr/code-server) as this has to deal with code-server and NOT sshcode

Can you try directly running the code-server binary on the remote, and seeing if these issues exist then? if they dont, then it is sshcode at fault,
